import {
  AlertTriangle,
  ArrowRight,
  Briefcase,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  Eye,
  File,
  FileText,
  HelpCircle,
  ImageIcon,
  Laptop,
  Layout,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  type LucideIcon,
  Sparkles,
  Palette,
  Globe,
  Code,
  Rocket,
  Zap,
  Github,
  Linkedin,
  Mail,
  Menu,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  check: Check,
  sparkles: Sparkles,
  palette: Palette,
  layout: Layout,
  globe: Globe,
  code: Code,
  rocket: Rocket,
  zap: Zap,
  linkedin: Linkedin,
  mail: Mail,
  menu: Menu,
  file: File,
  fileText: FileText,
  image: ImageIcon,
  eye: Eye,
  plus: Plus,
  briefcase: Briefcase,
}
